import type { HomeAssistant } from "./types";

type Lang = Pick<HomeAssistant, "language" | "locale">;

const en = {
  title: "House State",
  menu: "Open the sidebar",
  entry: "House",
  unsaved: "Unsaved changes",
  allSaved: "All changes saved",
  save: "Save",
  saving: "Saving…",
  discard: "Discard",
  cancel: "Cancel",
  close: "Close",
  retry: "Try again",
  reload: "Reload",
  loading: "Loading the configuration…",
  loadFailed: "Could not load the configuration",
  notConfiguredTitle: "No house set up yet",
  notConfiguredBody:
    "Add House State under Settings → Devices & services to create your first house. Its settings appear here afterwards.",
  addIntegration: "Add House State",
  saved: "Saved. House State reloads; no scenes were applied.",
  saveFailed: "Could not save",
  invalidTitle: "The configuration was not saved",
  conflict:
    "The settings were changed somewhere else since you opened them. Reload to see the saved version; your unsaved changes here are lost.",
  reloadDiscards: "Reload saved settings",
  warningsTitle: "Some scenes need attention",
  warningsBody:
    "These scenes or their members are missing in Home Assistant. You can save anyway and fix the scenes later. Saving never applies scenes.",
  saveAnyway: "Save anyway",
  leaveTitle: "Discard unsaved changes?",
  leaveBody: "Switching house throws away the changes you have not saved.",
  discardTitle: "Discard all changes?",
  discardBody: "The draft goes back to the saved settings.",
  issues: "{count} to fix",
  issuesOne: "1 to fix",
  sections: {
    states: "States",
    overlays: "Overlays",
    presence: "Presence & arrival",
    night: "Night",
    visits: "Visits",
    water: "Water",
    advanced: "Advanced",
  },
  sectionHints: {
    states: "The state tree, scenes, occupancy and roles",
    overlays: "Seasonal and manual scenes on top of the state",
    presence: "What counts as coming home and leaving",
    night: "When the night role starts by itself",
    visits: "Guest visits while nobody is home",
    water: "Valves closed during vacation",
    advanced: "Legacy helpers",
  },
  // States
  tree: "State tree",
  treeHint:
    "Selecting a state follows its default child. The scene comes from the nearest state that has one.",
  addTopLevel: "Add top-level state",
  addChild: "Add child state",
  deleteState: "Delete state",
  newState: "New state",
  selectState: "Select a state to edit it.",
  editState: "Edit state",
  name: "Name",
  id: "ID",
  idHint:
    "Lowercase letters, digits and underscores, starting with a letter. It cannot change after saving.",
  idFixed:
    "Fixed ID. Automations and entities use it, so it stays when you rename this.",
  parent: "Parent",
  topLevel: "— Top level",
  defaultChild: "Default child",
  noDefaultChild: "— None (stay on this state)",
  noChildren: "Add a child state to choose a default child.",
  scene: "Scene",
  noScene: "No scene",
  sceneInherits: "Inherits {scene} from {name}",
  sceneNone: "No scene on this path",
  sceneMissing: "Not found in Home Assistant",
  occupancy: "Occupancy",
  inherit: "Inherit",
  inherited: "inherited",
  someoneHome: "Someone home",
  nobodyHome: "Nobody home",
  inheritsFrom: "inherited from {name}",
  inheritedDefault: "nobody home unless a parent says otherwise",
  movesDefault: "Moving it clears the default child of {name}.",
  defaultBadge: "Default",
  defaultOf: "Default child of {name}",
  initialBadge: "Start",
  initialState: "Start state",
  initialHint: "Used when House State starts without a remembered state.",
  roles: "Roles",
  rolesHint:
    "Automations switch to these states. Arrival and night must lead to someone home; departure and vacation to nobody home.",
  roleOff: "— Off",
  role: {
    arrival: "Arrival",
    departure: "Departure",
    vacation: "Vacation",
    night: "Night",
  },
  roleNeedsHome: "{role} must lead to a state where someone is home",
  roleNeedsAway: "{role} must lead to a state where nobody is home",
  roleMissing: "{role} points to a state that no longer exists",
  leadsTo: "Leads to {name}",
  // Delete
  deleteTitle: "Delete {name}?",
  deleteIntro: "This changes the draft as follows:",
  deleteRemove: "{name} is removed.",
  deleteReparent: "{names} move to {parent}.",
  deleteReparentRoot: "{names} become top-level states.",
  deleteDefault: "{name} no longer has a default child.",
  deleteRole: "The {role} role is turned off.",
  deleteWhenState: "Overlay {name} no longer lists it among its states.",
  deleteInitial: "It is the start state. Choose a new start state:",
  deleteBlockedLast:
    "The last state cannot be deleted. Add another state first.",
  deleteBlockedOverlay:
    "Overlay {names} is only allowed in this state. Deleting it would make that overlay apply everywhere. Change the overlay first.",
  openOverlay: "Open {name}",
  delete: "Delete",
  // Overlays
  overlaysHint:
    "An overlay scene runs after the state's scene. Rules can switch an overlay on by calendar or date; the highest priority wins, then the order in this list.",
  addOverlay: "Add overlay",
  newOverlay: "New overlay",
  editOverlay: "Edit overlay",
  deleteOverlay: "Delete overlay",
  deleteOverlayTitle: "Delete overlay {name}?",
  deleteOverlayBody: "The overlay and its rule are removed from the draft.",
  noOverlays: "No overlays yet.",
  selectOverlay: "Select an overlay to edit it.",
  priority: "Priority",
  priorityHint: "−100 to 100; higher wins.",
  activation: "Activation",
  manual: "Manual",
  calendar: "Calendar",
  dates: "Dates",
  calendarEntity: "Calendar",
  match: "Event title pattern",
  matchHint:
    "Optional regular expression. Empty means any event in the calendar.",
  matchInvalid: "This pattern is not a valid regular expression",
  calendarRequired: "Choose a calendar",
  dateKind: "Kind of date",
  fixed: "Fixed dates",
  easter: "Around Easter",
  nthWeekday: "Weekday in a month",
  from: "From",
  to: "To",
  month: "Month",
  day: "Day",
  easterHint: "Days from Easter Sunday: −2 is Good Friday, 1 is Easter Monday.",
  easterFrom: "First day",
  easterTo: "Last day",
  easterOrder: "The first day must not come after the last day",
  occurrence: "Which",
  weekday: "Weekday",
  countFrom: "Counted",
  inMonth: "Within a month",
  fromDate: "From a date",
  anchor: "Date",
  lasts: "Lasts (days)",
  noSuchDay: "There is no such day",
  conditions: "Only when",
  whenOccupied: "Occupancy",
  any: "Any",
  whenState: "Only in these states",
  whenStateHint: "None selected means every state.",
  // Rule summary
  sumManual: "Manual only",
  sumCalendar: "Calendar: {calendar}",
  sumMatch: "{text} matching “{match}”",
  sumFixed: "Every year {from} → {to}",
  sumEaster: "Easter {from} to {to} days",
  sumEasterSunday: "Easter Sunday",
  sumNthMonth: "{nth} {weekday} in {month}",
  sumNthAfter: "{nth} {weekday} after {date}",
  sumNthBefore: "{nth} {weekday} before {date}",
  sumDays: "{text} for {days}",
  dayOne: "1 day",
  dayMany: "{count} days",
  sumHome: "Only when someone is home",
  sumAway: "Only when nobody is home",
  sumStates: "Only in: {states}",
  sumPriority: "Priority {priority}",
  ordinal: {
    "1": "1st",
    "2": "2nd",
    "3": "3rd",
    "4": "4th",
    "5": "5th",
    "-1": "last",
    "-2": "2nd to last",
    "-3": "3rd to last",
    "-4": "4th to last",
    "-5": "5th to last",
  } as Record<string, string>,
  ordinalAnchor: {
    "1": "1st",
    "2": "2nd",
    "3": "3rd",
    "4": "4th",
    "5": "5th",
    "-1": "1st",
    "-2": "2nd",
    "-3": "3rd",
    "-4": "4th",
    "-5": "5th",
  } as Record<string, string>,
  direction: "Before or after",
  before: "Before",
  after: "After",
  weekdays: {
    mon: "Monday",
    tue: "Tuesday",
    wed: "Wednesday",
    thu: "Thursday",
    fri: "Friday",
    sat: "Saturday",
    sun: "Sunday",
  } as Record<string, string>,
  weekdaysInline: {
    mon: "Monday",
    tue: "Tuesday",
    wed: "Wednesday",
    thu: "Thursday",
    fri: "Friday",
    sat: "Saturday",
    sun: "Sunday",
  } as Record<string, string>,
  months: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  monthsInline: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  // Presence
  presenceHint:
    "Unlocking a door or opening a gate counts as coming home. People tracked by Home Assistant can trigger arrival and departure.",
  doors: "Door locks",
  gates: "Gates",
  people: "People",
  autoReturn: "Automatic arrival",
  autoReturnHint:
    "Switch to the arrival state when a door or gate opens or a person comes home while nobody is.",
  autoAway: "Automatic departure",
  autoAwayHint:
    "Switch to the departure state when every person has left, after the waiting time.",
  awayGrace: "Wait before departure",
  arrivalDelay: "Arrival delay after a lock or gate",
  arrivalDelayHint:
    "Waits so a guest visit announced just after (for example from a door panel) is not mistaken for the family coming home. 0 means at once.",
  // Night
  nightHint: "Switch to the night role automatically.",
  schedule: "Schedule",
  off: "Off",
  fixedTime: "Fixed time",
  sun: "Sunset or sunrise",
  time: "Local time",
  sunEvent: "Sun event",
  sunset: "Sunset",
  sunrise: "Sunrise",
  offset: "Offset",
  minutes: "min",
  hours: "h",
  seconds: "s",
  nightAt: "Night starts at {time}.",
  nightSunExact: "Night starts at {event}.",
  nightSunBefore: "Night starts {offset} before {event}.",
  nightSunAfter: "Night starts {offset} after {event}.",
  nightOff: "Night only starts when someone chooses it.",
  nightRoleOff:
    "The night role is off, so the schedule has nothing to switch to. Choose a night state under States → Roles.",
  timeInvalid: "Enter a time",
  // Visits
  visitsHint:
    "A guest visit keeps the house in its unoccupied state while a guest is inside: arrival from locks and gates is ignored during the visit and the exit window after it. People still count and end the visit.",
  visitDuration: "Default visit length",
  visitMax: "Longest allowed visit",
  exitGrace: "Exit window after a visit",
  reapply: "Apply the scene again when a visit ends",
  reapplyHint: "Only while nobody is home.",
  visitLocks: "Locks to lock when a visit ends",
  durationOverMax: "The default visit is longer than the longest allowed visit",
  outOfRange: "Allowed: {min} to {max}",
  // Water
  waterHint:
    "Valves that close while the house is in the vacation state (or below it). A guest visit opens them while it lasts. Saving settings never operates valves.",
  valves: "Water valves",
  waterRoleOff:
    "The vacation role is off, so the valves never close. Choose a vacation state under States → Roles.",
  // Advanced
  legacy: "Legacy helpers",
  legacyHint:
    "Optional input_select helpers that mirror the chosen state and overlay, for older dashboards and automations. Leave empty to stop mirroring.",
  legacyState: "State mirror",
  legacyOverlay: "Overlay mirror",
  // Validation
  nameRequired: "Enter a name",
  nameTooLong: "Use at most 100 characters",
  idInvalid:
    "Use lowercase letters, digits and underscores, starting with a letter",
  idDuplicate: "Another item already uses this ID",
  idReserved: "none and auto are reserved",
  remove: "Remove {name}",
  addEntity: "Add",
  entityPlaceholder: "Entity ID",
  starterStates: {
    home: "Home",
    day: "Day",
    idle: "None",
    tv: "TV",
    eating: "Eating",
    night: "Night",
    away: "Away",
    vacation: "Vacation",
  } as Record<string, string>,
  starterOverlays: {
    christmas: "Christmas",
    halloween: "Halloween",
    party: "Party",
  } as Record<string, string>,
};

export type Strings = typeof en;

const nb: Strings = {
  title: "Hustilstand",
  menu: "Åpne sidepanelet",
  entry: "Hus",
  unsaved: "Endringer som ikke er lagret",
  allSaved: "Alle endringer er lagret",
  save: "Lagre",
  saving: "Lagrer …",
  discard: "Forkast",
  cancel: "Avbryt",
  close: "Lukk",
  retry: "Prøv igjen",
  reload: "Last inn på nytt",
  loading: "Henter innstillingene …",
  loadFailed: "Kunne ikke hente innstillingene",
  notConfiguredTitle: "Ingen hus er satt opp ennå",
  notConfiguredBody:
    "Legg til House State under Innstillinger → Enheter og tjenester for å opprette det første huset. Innstillingene vises her etterpå.",
  addIntegration: "Legg til House State",
  saved: "Lagret. House State lastes inn på nytt; ingen scener ble aktivert.",
  saveFailed: "Kunne ikke lagre",
  invalidTitle: "Innstillingene ble ikke lagret",
  conflict:
    "Innstillingene er endret et annet sted etter at du åpnet dem. Last inn på nytt for å se den lagrede versjonen; endringene du ikke har lagret her, går tapt.",
  reloadDiscards: "Last inn lagrede innstillinger",
  warningsTitle: "Noen scener trenger tilsyn",
  warningsBody:
    "Disse scenene eller entitetene i dem mangler i Home Assistant. Du kan lagre likevel og rette scenene senere. Lagring aktiverer aldri scener.",
  saveAnyway: "Lagre likevel",
  leaveTitle: "Forkaste endringene?",
  leaveBody: "Bytter du hus, forsvinner endringene du ikke har lagret.",
  discardTitle: "Forkaste alle endringer?",
  discardBody: "Utkastet går tilbake til de lagrede innstillingene.",
  issues: "{count} å rette",
  issuesOne: "1 å rette",
  sections: {
    states: "Tilstander",
    overlays: "Overlegg",
    presence: "Hjemkomst og avreise",
    night: "Natt",
    visits: "Gjestebesøk",
    water: "Vann",
    advanced: "Avansert",
  },
  sectionHints: {
    states: "Tilstandstreet, scener, tilstedeværelse og roller",
    overlays: "Sesong- og manuelle scener oppå tilstanden",
    presence: "Hva som teller som å komme hjem og dra",
    night: "Når nattrollen starter av seg selv",
    visits: "Gjestebesøk mens ingen er hjemme",
    water: "Ventiler som stenges i ferien",
    advanced: "Gamle hjelpeentiteter",
  },
  tree: "Tilstandstre",
  treeHint:
    "Når en tilstand velges, følges standardbarnet. Scenen hentes fra nærmeste tilstand som har en.",
  addTopLevel: "Legg til tilstand øverst",
  addChild: "Legg til undertilstand",
  deleteState: "Slett tilstand",
  newState: "Ny tilstand",
  selectState: "Velg en tilstand for å redigere den.",
  editState: "Rediger tilstand",
  name: "Navn",
  id: "ID",
  idHint:
    "Små bokstaver, tall og understrek, og start med en bokstav. Den kan ikke endres etter lagring.",
  idFixed:
    "Fast ID. Automatiseringer og entiteter bruker den, så den beholdes når du endrer navnet.",
  parent: "Forelder",
  topLevel: "— Øverst",
  defaultChild: "Standardbarn",
  noDefaultChild: "— Ingen (bli i denne tilstanden)",
  noChildren: "Legg til en undertilstand for å velge standardbarn.",
  scene: "Scene",
  noScene: "Ingen scene",
  sceneInherits: "Arver {scene} fra {name}",
  sceneNone: "Ingen scene på denne veien",
  sceneMissing: "Finnes ikke i Home Assistant",
  occupancy: "Tilstedeværelse",
  inherit: "Arv",
  inherited: "arvet",
  someoneHome: "Noen hjemme",
  nobodyHome: "Ingen hjemme",
  inheritsFrom: "arvet fra {name}",
  inheritedDefault: "ingen hjemme med mindre en forelder sier noe annet",
  movesDefault: "Flyttingen fjerner standardbarnet til {name}.",
  defaultBadge: "Standard",
  defaultOf: "Standardbarn for {name}",
  initialBadge: "Start",
  initialState: "Starttilstand",
  initialHint: "Brukes når House State starter uten en husket tilstand.",
  roles: "Roller",
  rolesHint:
    "Automatiseringer bytter til disse tilstandene. Hjemkomst og natt må føre til noen hjemme; avreise og ferie til ingen hjemme.",
  roleOff: "— Av",
  role: {
    arrival: "Hjemkomst",
    departure: "Avreise",
    vacation: "Ferie",
    night: "Natt",
  },
  roleNeedsHome: "{role} må føre til en tilstand med noen hjemme",
  roleNeedsAway: "{role} må føre til en tilstand uten noen hjemme",
  roleMissing: "{role} peker på en tilstand som ikke finnes lenger",
  leadsTo: "Fører til {name}",
  deleteTitle: "Slette {name}?",
  deleteIntro: "Dette endrer utkastet slik:",
  deleteRemove: "{name} fjernes.",
  deleteReparent: "{names} flyttes til {parent}.",
  deleteReparentRoot: "{names} flyttes øverst i treet.",
  deleteDefault: "{name} får ikke lenger noe standardbarn.",
  deleteRole: "Rollen {role} slås av.",
  deleteWhenState:
    "Overlegget {name} har den ikke lenger blant sine tilstander.",
  deleteInitial: "Den er starttilstand. Velg ny starttilstand:",
  deleteBlockedLast:
    "Den siste tilstanden kan ikke slettes. Legg til en annen tilstand først.",
  deleteBlockedOverlay:
    "Overlegget {names} er bare tillatt i denne tilstanden. Sletting ville gjort at overlegget gjelder overalt. Endre overlegget først.",
  openOverlay: "Åpne {name}",
  delete: "Slett",
  overlaysHint:
    "En overleggsscene kjøres etter scenen for tilstanden. Regler kan slå på et overlegg etter kalender eller dato; høyest prioritet vinner, deretter rekkefølgen i listen.",
  addOverlay: "Legg til overlegg",
  newOverlay: "Nytt overlegg",
  editOverlay: "Rediger overlegg",
  deleteOverlay: "Slett overlegg",
  deleteOverlayTitle: "Slette overlegget {name}?",
  deleteOverlayBody: "Overlegget og regelen fjernes fra utkastet.",
  noOverlays: "Ingen overlegg ennå.",
  selectOverlay: "Velg et overlegg for å redigere det.",
  priority: "Prioritet",
  priorityHint: "−100 til 100; høyest vinner.",
  activation: "Aktivering",
  manual: "Manuelt",
  calendar: "Kalender",
  dates: "Datoer",
  calendarEntity: "Kalender",
  match: "Mønster for hendelsestittel",
  matchHint:
    "Valgfritt regulært uttrykk. Tomt betyr alle hendelser i kalenderen.",
  matchInvalid: "Mønsteret er ikke et gyldig regulært uttrykk",
  calendarRequired: "Velg en kalender",
  dateKind: "Type dato",
  fixed: "Faste datoer",
  easter: "Rundt påske",
  nthWeekday: "Ukedag i en måned",
  from: "Fra",
  to: "Til",
  month: "Måned",
  day: "Dag",
  easterHint: "Dager fra påskedag: −2 er langfredag, 1 er andre påskedag.",
  easterFrom: "Første dag",
  easterTo: "Siste dag",
  easterOrder: "Første dag kan ikke komme etter siste dag",
  occurrence: "Hvilken",
  weekday: "Ukedag",
  countFrom: "Telles",
  inMonth: "Innenfor en måned",
  fromDate: "Fra en dato",
  anchor: "Dato",
  lasts: "Varer (dager)",
  noSuchDay: "Den dagen finnes ikke",
  conditions: "Bare når",
  whenOccupied: "Tilstedeværelse",
  any: "Uansett",
  whenState: "Bare i disse tilstandene",
  whenStateHint: "Ingen valgt betyr alle tilstander.",
  sumManual: "Bare manuelt",
  sumCalendar: "Kalender: {calendar}",
  sumMatch: "{text} som passer «{match}»",
  sumFixed: "Hvert år {from} → {to}",
  sumEaster: "Påske {from} til {to} dager",
  sumEasterSunday: "Påskedag",
  sumNthMonth: "{nth} {weekday} i {month}",
  sumNthAfter: "{nth} {weekday} etter {date}",
  sumNthBefore: "{nth} {weekday} før {date}",
  sumDays: "{text} i {days}",
  dayOne: "1 dag",
  dayMany: "{count} dager",
  sumHome: "Bare når noen er hjemme",
  sumAway: "Bare når ingen er hjemme",
  sumStates: "Bare i: {states}",
  sumPriority: "Prioritet {priority}",
  ordinal: {
    "1": "1.",
    "2": "2.",
    "3": "3.",
    "4": "4.",
    "5": "5.",
    "-1": "siste",
    "-2": "nest siste",
    "-3": "3. siste",
    "-4": "4. siste",
    "-5": "5. siste",
  },
  ordinalAnchor: {
    "1": "1.",
    "2": "2.",
    "3": "3.",
    "4": "4.",
    "5": "5.",
    "-1": "1.",
    "-2": "2.",
    "-3": "3.",
    "-4": "4.",
    "-5": "5.",
  },
  direction: "Før eller etter",
  before: "Før",
  after: "Etter",
  weekdays: {
    mon: "Mandag",
    tue: "Tirsdag",
    wed: "Onsdag",
    thu: "Torsdag",
    fri: "Fredag",
    sat: "Lørdag",
    sun: "Søndag",
  },
  weekdaysInline: {
    mon: "mandag",
    tue: "tirsdag",
    wed: "onsdag",
    thu: "torsdag",
    fri: "fredag",
    sat: "lørdag",
    sun: "søndag",
  },
  months: [
    "Januar",
    "Februar",
    "Mars",
    "April",
    "Mai",
    "Juni",
    "Juli",
    "August",
    "September",
    "Oktober",
    "November",
    "Desember",
  ],
  monthsInline: [
    "januar",
    "februar",
    "mars",
    "april",
    "mai",
    "juni",
    "juli",
    "august",
    "september",
    "oktober",
    "november",
    "desember",
  ],
  presenceHint:
    "Når en dør låses opp eller en port åpnes, teller det som hjemkomst. Personer som Home Assistant følger, kan utløse hjemkomst og avreise.",
  doors: "Låser for hjemkomst",
  gates: "Porter for hjemkomst",
  people: "Personer",
  autoReturn: "Automatisk hjemkomst",
  autoReturnHint:
    "Bytt til hjemkomsttilstanden når en dør eller port åpnes eller en person kommer hjem mens ingen er hjemme.",
  autoAway: "Automatisk avreise",
  autoAwayHint:
    "Bytt til avreisetilstanden når alle personene har dratt, etter ventetiden.",
  awayGrace: "Ventetid før avreise",
  arrivalDelay: "Forsinkelse for hjemkomst etter lås eller port",
  arrivalDelayHint:
    "Venter slik at et gjestebesøk som meldes like etter (for eksempel fra et dørpanel), ikke tolkes som at familien kommer hjem. 0 gir hjemkomst med én gang.",
  nightHint: "Bytt automatisk til nattrollen.",
  schedule: "Tidsplan",
  off: "Av",
  fixedTime: "Fast klokkeslett",
  sun: "Soloppgang eller solnedgang",
  time: "Lokalt klokkeslett",
  sunEvent: "Solhendelse",
  sunset: "Solnedgang",
  sunrise: "Soloppgang",
  offset: "Forskyvning",
  minutes: "min",
  hours: "t",
  seconds: "s",
  nightAt: "Natt starter kl. {time}.",
  nightSunExact: "Natt starter ved {event}.",
  nightSunBefore: "Natt starter {offset} før {event}.",
  nightSunAfter: "Natt starter {offset} etter {event}.",
  nightOff: "Natt starter bare når noen velger den.",
  nightRoleOff:
    "Nattrollen er av, så tidsplanen har ingenting å bytte til. Velg en natttilstand under Tilstander → Roller.",
  timeInvalid: "Skriv inn et klokkeslett",
  visitsHint:
    "Et gjestebesøk holder huset i ubebodd tilstand mens en gjest er inne: hjemkomst fra lås og port ignoreres under besøket og i utgangsvinduet etterpå. Personer teller fortsatt og avslutter besøket.",
  visitDuration: "Standard besøkslengde",
  visitMax: "Lengste tillatte besøk",
  exitGrace: "Utgangsvindu etter besøk",
  reapply: "Bruk scenen på nytt når besøket avsluttes",
  reapplyHint: "Bare mens ingen er hjemme.",
  visitLocks: "Låser som låses når besøket avsluttes",
  durationOverMax: "Standard besøk er lengre enn lengste tillatte besøk",
  outOfRange: "Tillatt: {min} til {max}",
  waterHint:
    "Ventiler som stenger vannet mens huset er i ferietilstanden (eller under den). Et gjestebesøk åpner vannet så lenge det varer. Lagring av innstillinger betjener aldri ventiler.",
  valves: "Vannventiler",
  waterRoleOff:
    "Ferierollen er av, så ventilene stenges aldri. Velg en ferietilstand under Tilstander → Roller.",
  legacy: "Gamle hjelpeentiteter",
  legacyHint:
    "Valgfrie input_select-hjelpere som speiler valgt tilstand og overlegg, for eldre dashbord og automatiseringer. La feltet stå tomt for å stoppe speilingen.",
  legacyState: "Speiling av tilstand",
  legacyOverlay: "Speiling av overlegg",
  nameRequired: "Skriv inn et navn",
  nameTooLong: "Bruk høyst 100 tegn",
  idInvalid: "Bruk små bokstaver, tall og understrek, og start med en bokstav",
  idDuplicate: "Denne ID-en er allerede i bruk",
  idReserved: "none og auto er reservert",
  remove: "Fjern {name}",
  addEntity: "Legg til",
  entityPlaceholder: "Entitets-ID",
  starterStates: {
    home: "Hjemme",
    day: "Dag",
    idle: "Ingen",
    tv: "TV",
    eating: "Spiser",
    night: "Natt",
    away: "Borte",
    vacation: "Ferie",
  },
  starterOverlays: { christmas: "Jul", halloween: "Halloween", party: "Fest" },
};

/** Translation language: nb, nb-NO, no and the nn fallback give Bokmål. */
export function language(hass?: Lang): "nb" | "en" {
  const value = String(hass?.language || hass?.locale?.language || "en")
    .toLowerCase()
    .replace(/_/g, "-");
  return /^(nb|no|nn)(-|$)/.test(value) ? "nb" : "en";
}

/** Formatting locale stays regional (en-GB keeps its clock) and never throws. */
export function formattingLocale(hass?: Lang): string {
  const requested = String(hass?.language || hass?.locale?.language || "en")
    .toLowerCase()
    .replace(/_/g, "-")
    .replace(/^(no|nn)(-|$)/, "nb$2");
  try {
    return Intl.getCanonicalLocales(requested)[0] || "en";
  } catch {
    return "en";
  }
}

export function localize(hass?: Lang): Strings {
  return language(hass) === "nb" ? nb : en;
}

/** Translate only unmodified starter names; stored data is never renamed. */
export function displayName(
  strings: Strings,
  item: { id: string; name: string },
  kind: "starterStates" | "starterOverlays",
): string {
  return en[kind][item.id] === item.name && strings[kind][item.id]
    ? strings[kind][item.id]
    : item.name;
}

export function fill(
  text: string,
  values: Record<string, string | number>,
): string {
  return text.replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? ""));
}
